clear all
clc

%% Parameters
p_s = 19.9;    % power satellite [43 dBm]
p_c = 0.398;   % power cellular [26 dBm]
p_b = 10.0;   % power backhaul [40 dBm]
zeta = 4;      % pathloss exponent

% Antenna pattern for backhaul point:
G1 = 1e2;
G0 = 1e-1;
Theta = pi/12;

vec_alpha = linspace(0, pi);
d_alpha = vec_alpha(2) - vec_alpha(1);

% Automation:
N_vec = [100, 500, 1000, 1500, 2000]; % number of satellites
h_vec = [500, 1000, 1500, 2000]*1e3; % orbit altitude

r_e= 6371e3;

lambda_c = 1e-6;
lambda_s = 1e-6;
lambda_b = 1e-7;

% Nakagami
m = 3;
mu = 1;
beta = (factorial(m))^(-1/m);

h = h_vec(2);
N = N_vec(5);

% for h = h_vec
%     for N  = N_vec
        display(h+"  "+N)
        % PDF [OK]
        f_alpha_vec = real(csvread('D:\Satellites\28GHz\data\alpha0\f_alpha_'+string(int32(h.*1e-3)) ...
            +'_'+string(N)+'.csv'));

        % Check: The PMF must sum to 1
        d_alpha = 1/sum(f_alpha_vec); % 0.0326

        G_vec_read = csvread("D:\Satellites\28GHz\data\gain.csv"); % dB scale or dBm? [DOUBT]
        G_vec = 10.^(G_vec_read./10.0); % absolute scale

        syms tau v x

        %% Interference from Earth Stations
        % [OK]
        S_1_1 = (f_alpha_vec(1) .* d_alpha ).*( 1 + (1./mu).*G_vec(1).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(2) .* d_alpha ).*( 1 + (1./mu).*G_vec(2).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(3) .* d_alpha ).*( 1 + (1./mu).*G_vec(3).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(4) .* d_alpha ).*( 1 + (1./mu).*G_vec(4).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(5) .* d_alpha ).*( 1 + (1./mu).*G_vec(5).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(6) .* d_alpha ).*( 1 + (1./mu).*G_vec(6).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(7) .* d_alpha ).*( 1 + (1./mu).*G_vec(7).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(8) .* d_alpha ).*( 1 + (1./mu).*G_vec(8).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(9) .* d_alpha ).*( 1 + (1./mu).*G_vec(9).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(10) .* d_alpha ).*( 1 + (1./mu).*G_vec(10).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(11) .* d_alpha ).*( 1 + (1./mu).*G_vec(11).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(12) .* d_alpha ).*( 1 + (1./mu).*G_vec(12).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(13) .* d_alpha ).*( 1 + (1./mu).*G_vec(13).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(14) .* d_alpha ).*( 1 + (1./mu).*G_vec(14).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(15) .* d_alpha ).*( 1 + (1./mu).*G_vec(15).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(16) .* d_alpha ).*( 1 + (1./mu).*G_vec(16).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(17) .* d_alpha ).*( 1 + (1./mu).*G_vec(17).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(18) .* d_alpha ).*( 1 + (1./mu).*G_vec(18).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(19) .* d_alpha ).*( 1 + (1./mu).*G_vec(19).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(20) .* d_alpha ).*( 1 + (1./mu).*G_vec(20).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(21) .* d_alpha ).*( 1 + (1./mu).*G_vec(21).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(22) .* d_alpha ).*( 1 + (1./mu).*G_vec(22).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(23) .* d_alpha ).*( 1 + (1./mu).*G_vec(23).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(24) .* d_alpha ).*( 1 + (1./mu).*G_vec(24).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(25) .* d_alpha ).*( 1 + (1./mu).*G_vec(25).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(26) .* d_alpha ).*( 1 + (1./mu).*G_vec(26).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(27) .* d_alpha ).*( 1 + (1./mu).*G_vec(27).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(28) .* d_alpha ).*( 1 + (1./mu).*G_vec(28).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(29) .* d_alpha ).*( 1 + (1./mu).*G_vec(29).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(30) .* d_alpha ).*( 1 + (1./mu).*G_vec(30).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(31) .* d_alpha ).*( 1 + (1./mu).*G_vec(31).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(32) .* d_alpha ).*( 1 + (1./mu).*G_vec(32).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(33) .* d_alpha ).*( 1 + (1./mu).*G_vec(33).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(34) .* d_alpha ).*( 1 + (1./mu).*G_vec(34).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(35) .* d_alpha ).*( 1 + (1./mu).*G_vec(35).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(36) .* d_alpha ).*( 1 + (1./mu).*G_vec(36).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(37) .* d_alpha ).*( 1 + (1./mu).*G_vec(37).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(38) .* d_alpha ).*( 1 + (1./mu).*G_vec(38).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(39) .* d_alpha ).*( 1 + (1./mu).*G_vec(39).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(40) .* d_alpha ).*( 1 + (1./mu).*G_vec(40).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(41) .* d_alpha ).*( 1 + (1./mu).*G_vec(41).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(42) .* d_alpha ).*( 1 + (1./mu).*G_vec(42).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(43) .* d_alpha ).*( 1 + (1./mu).*G_vec(43).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(44) .* d_alpha ).*( 1 + (1./mu).*G_vec(44).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(45) .* d_alpha ).*( 1 + (1./mu).*G_vec(45).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(46) .* d_alpha ).*( 1 + (1./mu).*G_vec(46).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(47) .* d_alpha ).*( 1 + (1./mu).*G_vec(47).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(48) .* d_alpha ).*( 1 + (1./mu).*G_vec(48).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(49) .* d_alpha ).*( 1 + (1./mu).*G_vec(49).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(50) .* d_alpha ).*( 1 + (1./mu).*G_vec(50).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(51) .* d_alpha ).*( 1 + (1./mu).*G_vec(51).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(52) .* d_alpha ).*( 1 + (1./mu).*G_vec(52).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(53) .* d_alpha ).*( 1 + (1./mu).*G_vec(53).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(54) .* d_alpha ).*( 1 + (1./mu).*G_vec(54).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(55) .* d_alpha ).*( 1 + (1./mu).*G_vec(55).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(56) .* d_alpha ).*( 1 + (1./mu).*G_vec(56).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(57) .* d_alpha ).*( 1 + (1./mu).*G_vec(57).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(58) .* d_alpha ).*( 1 + (1./mu).*G_vec(58).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(59) .* d_alpha ).*( 1 + (1./mu).*G_vec(59).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(60) .* d_alpha ).*( 1 + (1./mu).*G_vec(60).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(61) .* d_alpha ).*( 1 + (1./mu).*G_vec(61).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(62) .* d_alpha ).*( 1 + (1./mu).*G_vec(62).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(63) .* d_alpha ).*( 1 + (1./mu).*G_vec(63).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(64) .* d_alpha ).*( 1 + (1./mu).*G_vec(64).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(65) .* d_alpha ).*( 1 + (1./mu).*G_vec(65).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(66) .* d_alpha ).*( 1 + (1./mu).*G_vec(66).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(67) .* d_alpha ).*( 1 + (1./mu).*G_vec(67).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(68) .* d_alpha ).*( 1 + (1./mu).*G_vec(68).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(69) .* d_alpha ).*( 1 + (1./mu).*G_vec(69).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(70) .* d_alpha ).*( 1 + (1./mu).*G_vec(70).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(71) .* d_alpha ).*( 1 + (1./mu).*G_vec(71).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(72) .* d_alpha ).*( 1 + (1./mu).*G_vec(72).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(73) .* d_alpha ).*( 1 + (1./mu).*G_vec(73).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(74) .* d_alpha ).*( 1 + (1./mu).*G_vec(74).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(75) .* d_alpha ).*( 1 + (1./mu).*G_vec(75).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(76) .* d_alpha ).*( 1 + (1./mu).*G_vec(76).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(77) .* d_alpha ).*( 1 + (1./mu).*G_vec(77).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(78) .* d_alpha ).*( 1 + (1./mu).*G_vec(78).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(79) .* d_alpha ).*( 1 + (1./mu).*G_vec(79).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(80) .* d_alpha ).*( 1 + (1./mu).*G_vec(80).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(81) .* d_alpha ).*( 1 + (1./mu).*G_vec(81).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(82) .* d_alpha ).*( 1 + (1./mu).*G_vec(82).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(83) .* d_alpha ).*( 1 + (1./mu).*G_vec(83).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(84) .* d_alpha ).*( 1 + (1./mu).*G_vec(84).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(85) .* d_alpha ).*( 1 + (1./mu).*G_vec(85).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(86) .* d_alpha ).*( 1 + (1./mu).*G_vec(86).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(87) .* d_alpha ).*( 1 + (1./mu).*G_vec(87).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(88) .* d_alpha ).*( 1 + (1./mu).*G_vec(88).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(89) .* d_alpha ).*( 1 + (1./mu).*G_vec(89).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(90) .* d_alpha ).*( 1 + (1./mu).*G_vec(90).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(91) .* d_alpha ).*( 1 + (1./mu).*G_vec(91).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(92) .* d_alpha ).*( 1 + (1./mu).*G_vec(92).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(93) .* d_alpha ).*( 1 + (1./mu).*G_vec(93).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(94) .* d_alpha ).*( 1 + (1./mu).*G_vec(94).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(95) .* d_alpha ).*( 1 + (1./mu).*G_vec(95).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(96) .* d_alpha ).*( 1 + (1./mu).*G_vec(96).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(97) .* d_alpha ).*( 1 + (1./mu).*G_vec(97).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(98) .* d_alpha ).*( 1 + (1./mu).*G_vec(98).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(99) .* d_alpha ).*( 1 + (1./mu).*G_vec(99).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(100) .* d_alpha ).*( 1 + (1./mu).*G_vec(100).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m;


        
        S_1_2 = (f_alpha_vec(1) .* d_alpha ).*( 1 + (2./mu).*G_vec(1).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(2) .* d_alpha ).*( 1 + (2./mu).*G_vec(2).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(3) .* d_alpha ).*( 1 + (2./mu).*G_vec(3).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(4) .* d_alpha ).*( 1 + (2./mu).*G_vec(4).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(5) .* d_alpha ).*( 1 + (2./mu).*G_vec(5).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(6) .* d_alpha ).*( 1 + (2./mu).*G_vec(6).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(7) .* d_alpha ).*( 1 + (2./mu).*G_vec(7).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(8) .* d_alpha ).*( 1 + (2./mu).*G_vec(8).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(9) .* d_alpha ).*( 1 + (2./mu).*G_vec(9).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(10) .* d_alpha ).*( 1 + (2./mu).*G_vec(10).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(11) .* d_alpha ).*( 1 + (2./mu).*G_vec(11).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(12) .* d_alpha ).*( 1 + (2./mu).*G_vec(12).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(13) .* d_alpha ).*( 1 + (2./mu).*G_vec(13).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(14) .* d_alpha ).*( 1 + (2./mu).*G_vec(14).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(15) .* d_alpha ).*( 1 + (2./mu).*G_vec(15).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(16) .* d_alpha ).*( 1 + (2./mu).*G_vec(16).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(17) .* d_alpha ).*( 1 + (2./mu).*G_vec(17).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(18) .* d_alpha ).*( 1 + (2./mu).*G_vec(18).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(19) .* d_alpha ).*( 1 + (2./mu).*G_vec(19).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(20) .* d_alpha ).*( 1 + (2./mu).*G_vec(20).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(21) .* d_alpha ).*( 1 + (2./mu).*G_vec(21).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(22) .* d_alpha ).*( 1 + (2./mu).*G_vec(22).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(23) .* d_alpha ).*( 1 + (2./mu).*G_vec(23).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(24) .* d_alpha ).*( 1 + (2./mu).*G_vec(24).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(25) .* d_alpha ).*( 1 + (2./mu).*G_vec(25).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(26) .* d_alpha ).*( 1 + (2./mu).*G_vec(26).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(27) .* d_alpha ).*( 1 + (2./mu).*G_vec(27).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(28) .* d_alpha ).*( 1 + (2./mu).*G_vec(28).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(29) .* d_alpha ).*( 1 + (2./mu).*G_vec(29).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(30) .* d_alpha ).*( 1 + (2./mu).*G_vec(30).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(31) .* d_alpha ).*( 1 + (2./mu).*G_vec(31).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(32) .* d_alpha ).*( 1 + (2./mu).*G_vec(32).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(33) .* d_alpha ).*( 1 + (2./mu).*G_vec(33).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(34) .* d_alpha ).*( 1 + (2./mu).*G_vec(34).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(35) .* d_alpha ).*( 1 + (2./mu).*G_vec(35).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(36) .* d_alpha ).*( 1 + (2./mu).*G_vec(36).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(37) .* d_alpha ).*( 1 + (2./mu).*G_vec(37).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(38) .* d_alpha ).*( 1 + (2./mu).*G_vec(38).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(39) .* d_alpha ).*( 1 + (2./mu).*G_vec(39).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(40) .* d_alpha ).*( 1 + (2./mu).*G_vec(40).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(41) .* d_alpha ).*( 1 + (2./mu).*G_vec(41).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(42) .* d_alpha ).*( 1 + (2./mu).*G_vec(42).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(43) .* d_alpha ).*( 1 + (2./mu).*G_vec(43).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(44) .* d_alpha ).*( 1 + (2./mu).*G_vec(44).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(45) .* d_alpha ).*( 1 + (2./mu).*G_vec(45).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(46) .* d_alpha ).*( 1 + (2./mu).*G_vec(46).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(47) .* d_alpha ).*( 1 + (2./mu).*G_vec(47).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(48) .* d_alpha ).*( 1 + (2./mu).*G_vec(48).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(49) .* d_alpha ).*( 1 + (2./mu).*G_vec(49).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(50) .* d_alpha ).*( 1 + (2./mu).*G_vec(50).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(51) .* d_alpha ).*( 1 + (2./mu).*G_vec(51).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(52) .* d_alpha ).*( 1 + (2./mu).*G_vec(52).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(53) .* d_alpha ).*( 1 + (2./mu).*G_vec(53).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(54) .* d_alpha ).*( 1 + (2./mu).*G_vec(54).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(55) .* d_alpha ).*( 1 + (2./mu).*G_vec(55).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(56) .* d_alpha ).*( 1 + (2./mu).*G_vec(56).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(57) .* d_alpha ).*( 1 + (2./mu).*G_vec(57).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(58) .* d_alpha ).*( 1 + (2./mu).*G_vec(58).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(59) .* d_alpha ).*( 1 + (2./mu).*G_vec(59).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(60) .* d_alpha ).*( 1 + (2./mu).*G_vec(60).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(61) .* d_alpha ).*( 1 + (2./mu).*G_vec(61).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(62) .* d_alpha ).*( 1 + (2./mu).*G_vec(62).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(63) .* d_alpha ).*( 1 + (2./mu).*G_vec(63).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(64) .* d_alpha ).*( 1 + (2./mu).*G_vec(64).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(65) .* d_alpha ).*( 1 + (2./mu).*G_vec(65).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(66) .* d_alpha ).*( 1 + (2./mu).*G_vec(66).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(67) .* d_alpha ).*( 1 + (2./mu).*G_vec(67).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(68) .* d_alpha ).*( 1 + (2./mu).*G_vec(68).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(69) .* d_alpha ).*( 1 + (2./mu).*G_vec(69).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(70) .* d_alpha ).*( 1 + (2./mu).*G_vec(70).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(71) .* d_alpha ).*( 1 + (2./mu).*G_vec(71).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(72) .* d_alpha ).*( 1 + (2./mu).*G_vec(72).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(73) .* d_alpha ).*( 1 + (2./mu).*G_vec(73).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(74) .* d_alpha ).*( 1 + (2./mu).*G_vec(74).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(75) .* d_alpha ).*( 1 + (2./mu).*G_vec(75).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(76) .* d_alpha ).*( 1 + (2./mu).*G_vec(76).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(77) .* d_alpha ).*( 1 + (2./mu).*G_vec(77).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(78) .* d_alpha ).*( 1 + (2./mu).*G_vec(78).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(79) .* d_alpha ).*( 1 + (2./mu).*G_vec(79).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(80) .* d_alpha ).*( 1 + (2./mu).*G_vec(80).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(81) .* d_alpha ).*( 1 + (2./mu).*G_vec(81).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(82) .* d_alpha ).*( 1 + (2./mu).*G_vec(82).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(83) .* d_alpha ).*( 1 + (2./mu).*G_vec(83).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(84) .* d_alpha ).*( 1 + (2./mu).*G_vec(84).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(85) .* d_alpha ).*( 1 + (2./mu).*G_vec(85).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(86) .* d_alpha ).*( 1 + (2./mu).*G_vec(86).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(87) .* d_alpha ).*( 1 + (2./mu).*G_vec(87).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(88) .* d_alpha ).*( 1 + (2./mu).*G_vec(88).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(89) .* d_alpha ).*( 1 + (2./mu).*G_vec(89).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(90) .* d_alpha ).*( 1 + (2./mu).*G_vec(90).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(91) .* d_alpha ).*( 1 + (2./mu).*G_vec(91).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(92) .* d_alpha ).*( 1 + (2./mu).*G_vec(92).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(93) .* d_alpha ).*( 1 + (2./mu).*G_vec(93).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(94) .* d_alpha ).*( 1 + (2./mu).*G_vec(94).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(95) .* d_alpha ).*( 1 + (2./mu).*G_vec(95).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(96) .* d_alpha ).*( 1 + (2./mu).*G_vec(96).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(97) .* d_alpha ).*( 1 + (2./mu).*G_vec(97).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(98) .* d_alpha ).*( 1 + (2./mu).*G_vec(98).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(99) .* d_alpha ).*( 1 + (2./mu).*G_vec(99).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(100) .* d_alpha ).*( 1 + (2./mu).*G_vec(100).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m;

        
        
        S_1_3 = (f_alpha_vec(1) .* d_alpha ).*( 1 + (3./mu).*G_vec(1).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(2) .* d_alpha ).*( 1 + (3./mu).*G_vec(2).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(3) .* d_alpha ).*( 1 + (3./mu).*G_vec(3).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(4) .* d_alpha ).*( 1 + (3./mu).*G_vec(4).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(5) .* d_alpha ).*( 1 + (3./mu).*G_vec(5).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(6) .* d_alpha ).*( 1 + (3./mu).*G_vec(6).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(7) .* d_alpha ).*( 1 + (3./mu).*G_vec(7).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(8) .* d_alpha ).*( 1 + (3./mu).*G_vec(8).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(9) .* d_alpha ).*( 1 + (3./mu).*G_vec(9).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(10) .* d_alpha ).*( 1 + (3./mu).*G_vec(10).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(11) .* d_alpha ).*( 1 + (3./mu).*G_vec(11).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(12) .* d_alpha ).*( 1 + (3./mu).*G_vec(12).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(13) .* d_alpha ).*( 1 + (3./mu).*G_vec(13).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(14) .* d_alpha ).*( 1 + (3./mu).*G_vec(14).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(15) .* d_alpha ).*( 1 + (3./mu).*G_vec(15).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(16) .* d_alpha ).*( 1 + (3./mu).*G_vec(16).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(17) .* d_alpha ).*( 1 + (3./mu).*G_vec(17).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(18) .* d_alpha ).*( 1 + (3./mu).*G_vec(18).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(19) .* d_alpha ).*( 1 + (3./mu).*G_vec(19).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(20) .* d_alpha ).*( 1 + (3./mu).*G_vec(20).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(21) .* d_alpha ).*( 1 + (3./mu).*G_vec(21).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(22) .* d_alpha ).*( 1 + (3./mu).*G_vec(22).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(23) .* d_alpha ).*( 1 + (3./mu).*G_vec(23).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(24) .* d_alpha ).*( 1 + (3./mu).*G_vec(24).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(25) .* d_alpha ).*( 1 + (3./mu).*G_vec(25).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(26) .* d_alpha ).*( 1 + (3./mu).*G_vec(26).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(27) .* d_alpha ).*( 1 + (3./mu).*G_vec(27).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(28) .* d_alpha ).*( 1 + (3./mu).*G_vec(28).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(29) .* d_alpha ).*( 1 + (3./mu).*G_vec(29).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(30) .* d_alpha ).*( 1 + (3./mu).*G_vec(30).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(31) .* d_alpha ).*( 1 + (3./mu).*G_vec(31).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(32) .* d_alpha ).*( 1 + (3./mu).*G_vec(32).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(33) .* d_alpha ).*( 1 + (3./mu).*G_vec(33).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(34) .* d_alpha ).*( 1 + (3./mu).*G_vec(34).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(35) .* d_alpha ).*( 1 + (3./mu).*G_vec(35).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(36) .* d_alpha ).*( 1 + (3./mu).*G_vec(36).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(37) .* d_alpha ).*( 1 + (3./mu).*G_vec(37).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(38) .* d_alpha ).*( 1 + (3./mu).*G_vec(38).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(39) .* d_alpha ).*( 1 + (3./mu).*G_vec(39).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(40) .* d_alpha ).*( 1 + (3./mu).*G_vec(40).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(41) .* d_alpha ).*( 1 + (3./mu).*G_vec(41).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(42) .* d_alpha ).*( 1 + (3./mu).*G_vec(42).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(43) .* d_alpha ).*( 1 + (3./mu).*G_vec(43).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(44) .* d_alpha ).*( 1 + (3./mu).*G_vec(44).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(45) .* d_alpha ).*( 1 + (3./mu).*G_vec(45).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(46) .* d_alpha ).*( 1 + (3./mu).*G_vec(46).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(47) .* d_alpha ).*( 1 + (3./mu).*G_vec(47).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(48) .* d_alpha ).*( 1 + (3./mu).*G_vec(48).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(49) .* d_alpha ).*( 1 + (3./mu).*G_vec(49).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(50) .* d_alpha ).*( 1 + (3./mu).*G_vec(50).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(51) .* d_alpha ).*( 1 + (3./mu).*G_vec(51).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(52) .* d_alpha ).*( 1 + (3./mu).*G_vec(52).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(53) .* d_alpha ).*( 1 + (3./mu).*G_vec(53).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(54) .* d_alpha ).*( 1 + (3./mu).*G_vec(54).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(55) .* d_alpha ).*( 1 + (3./mu).*G_vec(55).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(56) .* d_alpha ).*( 1 + (3./mu).*G_vec(56).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(57) .* d_alpha ).*( 1 + (3./mu).*G_vec(57).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(58) .* d_alpha ).*( 1 + (3./mu).*G_vec(58).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(59) .* d_alpha ).*( 1 + (3./mu).*G_vec(59).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(60) .* d_alpha ).*( 1 + (3./mu).*G_vec(60).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(61) .* d_alpha ).*( 1 + (3./mu).*G_vec(61).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(62) .* d_alpha ).*( 1 + (3./mu).*G_vec(62).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(63) .* d_alpha ).*( 1 + (3./mu).*G_vec(63).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(64) .* d_alpha ).*( 1 + (3./mu).*G_vec(64).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(65) .* d_alpha ).*( 1 + (3./mu).*G_vec(65).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(66) .* d_alpha ).*( 1 + (3./mu).*G_vec(66).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(67) .* d_alpha ).*( 1 + (3./mu).*G_vec(67).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(68) .* d_alpha ).*( 1 + (3./mu).*G_vec(68).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(69) .* d_alpha ).*( 1 + (3./mu).*G_vec(69).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(70) .* d_alpha ).*( 1 + (3./mu).*G_vec(70).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(71) .* d_alpha ).*( 1 + (3./mu).*G_vec(71).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(72) .* d_alpha ).*( 1 + (3./mu).*G_vec(72).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(73) .* d_alpha ).*( 1 + (3./mu).*G_vec(73).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(74) .* d_alpha ).*( 1 + (3./mu).*G_vec(74).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(75) .* d_alpha ).*( 1 + (3./mu).*G_vec(75).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(76) .* d_alpha ).*( 1 + (3./mu).*G_vec(76).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(77) .* d_alpha ).*( 1 + (3./mu).*G_vec(77).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(78) .* d_alpha ).*( 1 + (3./mu).*G_vec(78).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(79) .* d_alpha ).*( 1 + (3./mu).*G_vec(79).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(80) .* d_alpha ).*( 1 + (3./mu).*G_vec(80).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(81) .* d_alpha ).*( 1 + (3./mu).*G_vec(81).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(82) .* d_alpha ).*( 1 + (3./mu).*G_vec(82).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(83) .* d_alpha ).*( 1 + (3./mu).*G_vec(83).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(84) .* d_alpha ).*( 1 + (3./mu).*G_vec(84).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(85) .* d_alpha ).*( 1 + (3./mu).*G_vec(85).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(86) .* d_alpha ).*( 1 + (3./mu).*G_vec(86).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(87) .* d_alpha ).*( 1 + (3./mu).*G_vec(87).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(88) .* d_alpha ).*( 1 + (3./mu).*G_vec(88).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(89) .* d_alpha ).*( 1 + (3./mu).*G_vec(89).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(90) .* d_alpha ).*( 1 + (3./mu).*G_vec(90).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(91) .* d_alpha ).*( 1 + (3./mu).*G_vec(91).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(92) .* d_alpha ).*( 1 + (3./mu).*G_vec(92).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(93) .* d_alpha ).*( 1 + (3./mu).*G_vec(93).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(94) .* d_alpha ).*( 1 + (3./mu).*G_vec(94).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(95) .* d_alpha ).*( 1 + (3./mu).*G_vec(95).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(96) .* d_alpha ).*( 1 + (3./mu).*G_vec(96).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(97) .* d_alpha ).*( 1 + (3./mu).*G_vec(97).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(98) .* d_alpha ).*( 1 + (3./mu).*G_vec(98).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(99) .* d_alpha ).*( 1 + (3./mu).*G_vec(99).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m ...
            + (f_alpha_vec(100) .* d_alpha ).*( 1 + (3./mu).*G_vec(100).*beta.*tau.*(p_s./p_c).*(v./x).^zeta )^-m;

        
        
        %% 
        I_2_1 =  vpaintegral( (1 - S_1_1).*x, x, [0 Inf]); % [OK]
        I_2_2 =  vpaintegral( (1 - S_1_2).*x, x, [0 Inf]); % [OK]
        I_2_3 =  vpaintegral( (1 - S_1_3).*x, x, [0 Inf]); % [OK]

        %%       
        L_Is_1 = exp(-2.*pi.*lambda_s.*I_2_1); % [OK]
        L_Is_2 = exp(-2.*pi.*lambda_s.*I_2_2); % [OK]
        L_Is_3 = exp(-2.*pi.*lambda_s.*I_2_3); % [OK]
        
        %% Interference from Backhaul Points
        S_b_1 = (Theta/pi)*(1 + 1.*G1.*(p_b./p_c).*beta.*tau.*(v./x).^zeta ).^-m ...
            + (1 - Theta/pi)*(1 + 1.*G0.*(p_b./p_c).*beta.*tau.*(v./x).^zeta ).^-m;
        
        S_b_2 = (Theta/pi)*(1 + 2.*G1.*(p_b./p_c).*beta.*tau.*(v./x).^zeta ).^-m ...
            + (1 - Theta/pi)*(1 + 2.*G0.*(p_b./p_c).*beta.*tau.*(v./x).^zeta ).^-m;
        
        S_b_3 = (Theta/pi)*(1 + 3.*G1.*(p_b./p_c).*beta.*tau.*(v./x).^zeta ).^-m ...
            + (1 - Theta/pi)*(1 + 3.*G0.*(p_b./p_c).*beta.*tau.*(v./x).^zeta ).^-m;
        
        I_b_1 =  vpaintegral( (1 - S_b_1).*x, x, [0 Inf]); % [OK]
        I_b_2 =  vpaintegral( (1 - S_b_2).*x, x, [0 Inf]); % [OK]
        I_b_3 =  vpaintegral( (1 - S_b_3).*x, x, [0 Inf]); % [OK]
        
        L_Ib_1 = exp(-2.*pi.*lambda_b.*I_b_1); % [OK]
        L_Ib_2 = exp(-2.*pi.*lambda_b.*I_b_2); % [OK]
        L_Ib_3 = exp(-2.*pi.*lambda_b.*I_b_3); % [OK]

        %% Interference from Cellular Base Stations
        S_2_1 =  (1 - (1 + (1/mu).*beta.*tau.*(v./x).^zeta ).^-m ).*x; % [OK]
        S_2_2 =  (1 - (1 + (2/mu).*beta.*tau.*(v./x).^zeta ).^-m ).*x; % [OK]
        S_2_3 =  (1 - (1 + (3/mu).*beta.*tau.*(v./x).^zeta ).^-m ).*x; % [OK]
        
        I_3_1 = vpaintegral(S_2_1, x, [v Inf]); % [OK]
        I_3_2 = vpaintegral(S_2_2, x, [v Inf]); % [OK]
        I_3_3 = vpaintegral(S_2_3, x, [v Inf]); % [OK]
        
        L_Ic_1 = exp(-2.*pi.*lambda_c.*I_3_1); % [OK]
        L_Ic_2 = exp(-2.*pi.*lambda_c.*I_3_2); % [OK]
        L_Ic_3 = exp(-2.*pi.*lambda_c.*I_3_3); % [OK]

        %% Coverage probability:
        % P_c_pre_int = 2.*pi.*lambda_c.*v.*exp(-pi.*lambda_c.*v.^2).*L_Is.*L_Ic; % [OK]
        % P_c = vpaintegral(P_c_pre_int, 0, Inf) % [OK]

%         prob_v = 2.*pi.*lambda_c.*v.*exp(-pi.*lambda_c.*v.^2);

        %% Evaluate P_c
        % Check: P_c(0) should be 1 [OK]

        v_val_vec = [1.0: 1.0: 1e6];
        F_v = @(z) exp(-pi.*lambda_c.*z.^2);
        F_v_vec = F_v(v_val_vec);

        iter = 1e2;

        tau_vec_dB = [-20:5:5];
        tau_vec_abs = 10.^(tau_vec_dB./10.0);
        P_c_vec = zeros(1, length(tau_vec_abs));

        for j = 1: length(tau_vec_abs)
            tau_val = tau_vec_abs(j);
            
            S_vec_1 = zeros(1, iter);
            S_vec_2 = zeros(1, iter);
            S_vec_3 = zeros(1, iter);
            
            tic
            for i= 1:iter
                u = rand(1);
                [min_val, index] = min(abs(F_v_vec - u));
                try
                    L_Is_1_mc = vpa(subs(L_Is_1, {tau, v}, {tau_val, v_val_vec(index)}));
                    L_Ic_1_mc = vpa(subs(L_Ic_1, {tau, v}, {tau_val, v_val_vec(index)}));
                    L_Ib_1_mc = vpa(subs(L_Ib_1, {tau, v}, {tau_val, v_val_vec(index)}));
                    
                    L_Is_2_mc = vpa(subs(L_Is_2, {tau, v}, {tau_val, v_val_vec(index)}));
                    L_Ic_2_mc = vpa(subs(L_Ic_2, {tau, v}, {tau_val, v_val_vec(index)}));
                    L_Ib_2_mc = vpa(subs(L_Ib_2, {tau, v}, {tau_val, v_val_vec(index)}));
                    
                    L_Is_3_mc = vpa(subs(L_Is_3, {tau, v}, {tau_val, v_val_vec(index)}));
                    L_Ic_3_mc = vpa(subs(L_Ic_3, {tau, v}, {tau_val, v_val_vec(index)}));
                    L_Ib_3_mc = vpa(subs(L_Ib_3, {tau, v}, {tau_val, v_val_vec(index)}));

                    S_vec_1(i) = L_Is_1_mc*L_Ic_1_mc*L_Ib_1_mc;
                    S_vec_2(i) = L_Is_2_mc*L_Ic_2_mc*L_Ib_2_mc;
                    S_vec_3(i) = L_Is_3_mc*L_Ic_3_mc*L_Ib_3_mc;
                    
                catch
                    S_vec_1(i) = NaN;
                    S_vec_2(i) = NaN;
                    S_vec_3(i) = NaN;
                end
            end
            toc

            p1 = mean(S_vec_1(~isnan(S_vec_1)));
            p2 = mean(S_vec_2(~isnan(S_vec_2)));
            p3 = mean(S_vec_3(~isnan(S_vec_3)));
            
            P_c_vec(j) = 3*p1 - 3*p2 + p3;
        end

        %% Save P_c_vec
        csvwrite('D:\Satellites\28GHz\data\coverage\P_c_'+string(int32(h*1e-3))+'_'+string(N)+'.csv', ...
                    P_c_vec);

      
%     end
% end


%% Figure
figure;
plot(tau_vec_dB, P_c_vec, 's-', 'LineWidth', 1.5)
xlabel('SIR [dB]')
ylabel('Coverage Probability')
title('h = '+ string(int32(h.*1e-3)) +' km, N = '+string(N))
% ylim([0 1])
xlim([-20 20])

